apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-databases
  annotations:
    mazelab.github.io/kindpro: "databases"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mazelab/kindpro-databases.git
    path: charts/_root
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
