apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "mysql-auth"
  namespace: kindpro-databases
  labels:
    kindpro.mazelab.github.io/repo: "kindpro-databases"
spec:
  refreshInterval: "0"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: random-24digits
  target:
    template:
      type: Opaque
      engineVersion: "v2"
      data:
        mysql-root-passsword: "{{ `{{ .password }}` }}"
